# Generated by Django 5.2.3 on 2026-03-23 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cover_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Friendship", "Friendship"),
                    ("Dating", "Dating"),
                    ("LongTerm", "Long-term Relationship"),
                    ("Marriage", "Marriage"),
                ],
                help_text="User's relationship goal",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user_images/")),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers"),
                            ("secret", "Secret"),
                        ],
                        default="followers",
                        max_length=10,
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile Picture"),
                            ("cover", "Cover Photo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_images",
                "unique_together": {("user", "image_type")},
            },
        ),
    ]
