# Generated by Django 5.2.3 on 2026-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_personalityquestion_user_last_seen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityTypeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mbti_type",
                    models.CharField(
                        choices=[
                            ("INTJ", "INTJ - The Architect"),
                            ("INTP", "INTP - The Logician"),
                            ("ENTJ", "ENTJ - The Commander"),
                            ("ENTP", "ENTP - The Debater"),
                            ("INFJ", "INFJ - The Advocate"),
                            ("INFP", "INFP - The Mediator"),
                            ("ENFJ", "ENFJ - The Protagonist"),
                            ("ENFP", "ENFP - The Campaigner"),
                            ("ISTJ", "ISTJ - The Logistician"),
                            ("ISFJ", "ISFJ - The Defender"),
                            ("ESTJ", "ESTJ - The Executive"),
                            ("ESFJ", "ESFJ - The Consul"),
                            ("ISTP", "ISTP - The Virtuoso"),
                            ("ISFP", "ISFP - The Adventurer"),
                            ("ESTP", "ESTP - The Entrepreneur"),
                            ("ESFP", "ESFP - The Entertainer"),
                        ],
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("career_matches", models.JSONField(default=list)),
                ("relationship_advice", models.TextField(blank=True)),
                (
                    "compatible_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of MBTI types that are compatible with this type",
                    ),
                ),
                ("fun_facts", models.JSONField(blank=True, default=list)),
                ("famous_people", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personality Type Detail",
                "verbose_name_plural": "Personality Type Details",
                "ordering": ["mbti_type"],
            },
        ),
    ]
