# Generated by Django 5.2.3 on 2026-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usersecuritysettings_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginsession",
            name="user_agent",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
