# Generated by Django 5.2.3 on 2026-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_personalitytypedetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_name_change_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time first_name or last_name was changed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True,
                help_text="Middle name (optional)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("update_profile", "Update Profile"),
                    ("create_post", "Create Post"),
                    ("like_post", "Like Post"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("unfollow", "Unfollow"),
                    ("join_group", "Join Group"),
                    ("leave_group", "Leave Group"),
                    ("admin_created_account", "Admin Created Account"),
                    ("admin_profile_update", "Admin Profile Update"),
                    ("admin_bulk_activate", "Admin Bulk Activate"),
                    ("admin_bulk_deactivate", "Admin Bulk Deactivate"),
                    ("admin_bulk_soft_delete", "Admin Bulk Soft Delete"),
                    ("admin_bulk_hard_delete", "Admin Bulk Hard Delete"),
                    ("admin_bulk_verify", "Admin Bulk Verify"),
                    ("admin_bulk_unverify", "Admin Bulk Unverify"),
                    ("bulk_session_termination", "Bulk Session Termination"),
                    ("session_terminated", "Session Terminated"),
                    ("account_created", "Account Created"),
                    ("follow_user", "Follow User"),
                    ("unfollow_user", "Unfollow User"),
                    ("profile_picture_update", "Profile Picture Update"),
                    ("profile_picture_removed", "Profile Picture Removed"),
                    ("cover_photo_update", "Cover Photo Update"),
                    ("cover_photo_removed", "Cover Photo Removed"),
                    ("password_change", "Password Change"),
                    ("status_change", "Status Change"),
                    ("2fa_enabled", "Two-Factor Authentication Enabled"),
                    ("2fa_disabled", "Two-Factor Authentication Disabled"),
                    ("security_settings_update", "Security Settings Update"),
                    ("update_email", "Update Email"),
                    ("update_phone", "Update Phone Number"),
                    ("update_username", "Update Username"),
                    ("update_full_name", "Update Full Name"),
                ],
                max_length=50,
            ),
        ),
    ]
