# Generated by Django 5.2.3 on 2026-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_loginsession_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
