# Generated by Django 5.2.3 on 2026-03-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attending_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="declined_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="maybe_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="EventAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rsvp_going_count", models.IntegerField(default=0)),
                ("rsvp_maybe_count", models.IntegerField(default=0)),
                ("rsvp_declined_count", models.IntegerField(default=0)),
                ("rsvp_changes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_analytics",
                "ordering": ["-date"],
                "unique_together": {("event", "date")},
            },
        ),
    ]
