# Generated by Django 5.2.3 on 2026-03-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
