# Generated by Django 5.2.3 on 2026-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="client_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="processing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="temp_file_paths",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
