# Generated by Django 5.2.3 on 2026-03-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("new_posts", models.IntegerField(default=0)),
                ("new_groups", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("pending_reports", models.IntegerField(default=0)),
                ("reviewed_reports", models.IntegerField(default=0)),
                ("resolved_reports", models.IntegerField(default=0)),
                ("dismissed_reports", models.IntegerField(default=0)),
                ("active_stories", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "platform_analytics",
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("posts_count", models.IntegerField(default=0)),
                ("likes_received", models.IntegerField(default=0)),
                ("comments_received", models.IntegerField(default=0)),
                ("new_followers", models.IntegerField(default=0)),
                ("stories_posted", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_analytics",
            },
        ),
        migrations.CreateModel(
            name="ObjectTrendScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("score", models.FloatField(default=0.0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
