# Generated by Django 5.2.3 on 2026-03-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useranalytics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="objecttrendscore",
            index=models.Index(fields=["score"], name="analytics_o_score_48c256_idx"),
        ),
        migrations.AddIndex(
            model_name="objecttrendscore",
            index=models.Index(
                fields=["calculated_at"], name="analytics_o_calcula_37b248_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="objecttrendscore",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="useranalytics",
            unique_together={("user", "date")},
        ),
    ]
