# Generated by Django 5.2.3 on 2026-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformanalytics",
            name="active_stories",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformanalytics",
            name="dismissed_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformanalytics",
            name="pending_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformanalytics",
            name="resolved_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformanalytics",
            name="reviewed_reports",
            field=models.IntegerField(default=0),
        ),
    ]
