# Generated by Django 5.2.3 on 2026-03-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_ban", "User Ban"),
                            ("user_warn", "User Warning"),
                            ("post_remove", "Post Removal"),
                            ("group_remove", "Group Removal"),
                            ("content_review", "Content Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "admin_logs",
            },
        ),
        migrations.CreateModel(
            name="ReportedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "reported_content",
            },
        ),
    ]
