# Generated by Django 5.2.3 on 2026-03-25 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_pannel", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportedcontent",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="reportedcontent",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="reported_co_content_a93cfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportedcontent",
            index=models.Index(fields=["status"], name="reported_co_status_bc30c6_idx"),
        ),
    ]
