# Generated by Django 5.2.3 on 2026-03-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storyhighlight",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_for_highlights",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="storyhighlight",
            name="stories",
            field=models.ManyToManyField(related_name="highlights", to="stories.story"),
        ),
        migrations.AddField(
            model_name="storyhighlight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_highlights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="storyhighlight",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_user_highlight_title"
            ),
        ),
    ]
