# Generated by Django 5.2.3 on 2026-04-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="story_thumbnails/"
            ),
        ),
    ]
