# Generated by Django 5.2.3 on 2026-03-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_storyhighlight"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoryView",
        ),
    ]
