# Generated by Django 5.2.3 on 2026-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_delete_storyview"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
