# Generated by Django 5.2.3 on 2026-04-10 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feed", "0005_post_is_archived_reel_is_archived_share_is_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="live/thumbnails/"
                    ),
                ),
                ("allow_requests", models.BooleanField(default=True)),
                ("max_participants", models.PositiveIntegerField(default=10)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "stream_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_lives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_recording",
                        to="feed.media",
                    ),
                ),
            ],
            options={
                "db_table": "live_streams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co‑host"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "live",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="live.livestream",
                    ),
                ),
            ],
            options={
                "db_table": "live_participants",
            },
        ),
        migrations.CreateModel(
            name="LiveJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "live",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="live.livestream",
                    ),
                ),
            ],
            options={
                "db_table": "live_join_requests",
                "ordering": ["requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["status", "started_at"], name="live_stream_status_148878_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["host", "status"], name="live_stream_host_id_48c2a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liveparticipant",
            index=models.Index(
                fields=["live", "role"], name="live_partic_live_id_0da3b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="liveparticipant",
            unique_together={("live", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="livejoinrequest",
            unique_together={("live", "user")},
        ),
    ]
