# Generated by Django 5.2.3 on 2026-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="host_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="livestream",
            name="livekit_room",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
