# Generated by Django 5.2.3 on 2026-04-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0002_livestream_host_token_livestream_livekit_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="host_token",
            field=models.TextField(blank=True),
        ),
    ]
