# Generated by Django 5.2.3 on 2026-03-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="chat_media/"),
        ),
        migrations.AddField(
            model_name="message",
            name="media_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
