# Generated by Django 5.2.3 on 2026-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dating_messages",
            },
        ),
        migrations.CreateModel(
            name="DatingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_age_min", models.IntegerField(blank=True, null=True)),
                ("preferred_age_max", models.IntegerField(blank=True, null=True)),
                (
                    "preferred_gender",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("max_distance_km", models.IntegerField(blank=True, null=True)),
                ("personality_match", models.BooleanField(default=False)),
                ("love_language_match", models.BooleanField(default=False)),
                ("relationship_goal_match", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dating_preferences",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "matches",
            },
        ),
    ]
