# Generated by Django 5.2.3 on 2026-03-28 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("SOFT_DELETE", "Soft Delete"),
                            ("RESTORE", "Restore"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the affected model.",
                        max_length=100,
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary key of the affected record.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Previous state (for UPDATE/DELETE).",
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="New state (for CREATE/UPDATE).",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional additional description."
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
