# Generated by Django 5.2.3 on 2026-03-27 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0001_initial"),
        ("groups", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediavariant",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="feed.media",
            ),
        ),
        migrations.AddField(
            model_name="objectbookmark",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="objectbookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="objectview",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="objectview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="feed.post",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "caption",
                    models.TextField(
                        blank=True, help_text="Optional message when sharing"
                    ),
                ),
            ],
            options={
                "db_table": "shares",
                "ordering": ["-created_at"],
            },
            bases=("feed.post",),
        ),
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="shared_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shares",
                to="feed.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tag_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id"], name="comments_content_cd20f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["content_type", "object_id"], name="media_content_a5c40c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediavariant",
            unique_together={("media", "variant_type")},
        ),
        migrations.AddIndex(
            model_name="objectbookmark",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="feed_object_content_47eb08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="objectbookmark",
            index=models.Index(fields=["user"], name="feed_object_user_id_fa90c5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="objectbookmark",
            unique_together={("user", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="objectview",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="feed_object_content_a2d0d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="objectview",
            index=models.Index(fields=["user"], name="feed_object_user_id_f89ef3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="objectview",
            unique_together={("user", "content_type", "object_id")},
        ),
        migrations.AddField(
            model_name="share",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "created_at"], name="posts_user_id_6b02c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["group", "created_at"], name="posts_group_i_9c0479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["content_type", "object_id"], name="likes_content_8cb9c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
