# Generated by Django 5.2.3 on 2026-03-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_initial"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="groups.group",
            ),
        ),
    ]
