# Generated by Django 5.2.3 on 2026-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
