# Generated by Django 5.2.3 on 2026-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="client_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="processing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="temp_file_paths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reel",
            name="client_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="reel",
            name="processing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reel",
            name="temp_file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
