# Generated by Django 5.2.3 on 2026-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_post_client_id_post_processing_post_temp_file_paths_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediavariant",
            name="variant_type",
            field=models.CharField(
                choices=[
                    ("thumbnail", "Thumbnail"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("video_preview", "Video Preview"),
                    ("video_transcoded", "Video Transcoded"),
                    ("video_480p", "480p Video"),
                    ("video_720p", "720p Video"),
                    ("video_1080p", "1080p Video"),
                ],
                max_length=30,
            ),
        ),
    ]
