# Generated by Django 5.2.3 on 2026-03-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_comment_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_public",
        ),
        migrations.AddField(
            model_name="post",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers"),
                    ("only_me", "Only-Me"),
                ],
                default="followers",
                max_length=10,
            ),
        ),
    ]
