# Generated by Django 5.2.3 on 2026-03-26 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_objectbookmark_objectview"),
        ("groups", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("dislike", "Dislike"),
                    ("love", "Love"),
                    ("care", "Care"),
                    ("haha", "Haha"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                ],
                default="like",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "created_at"], name="posts_user_id_6b02c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["group", "created_at"], name="posts_group_i_9c0479_idx"
            ),
        ),
    ]
