# Generated by Django 5.2.3 on 2026-04-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_alter_mediavariant_variant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reel",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="share",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
