# Generated by Django 5.2.3 on 2026-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_remove_post_is_public_post_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers"),
                    ("secret", "Secret"),
                ],
                default="followers",
                max_length=10,
            ),
        ),
    ]
