# Generated by Django 5.2.3 on 2026-04-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_post_is_archived_reel_is_archived_share_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="feeling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("love", "Love"),
                    ("crazy", "Crazy"),
                    ("cool", "Cool"),
                    ("excited", "Excited"),
                    ("angry", "Angry"),
                    ("bored", "Bored"),
                    ("tired", "Tired"),
                    ("confused", "Confused"),
                    ("anxious", "Anxious"),
                    ("proud", "Proud"),
                    ("lonely", "Lonely"),
                    ("blessed", "Blessed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("poll", "Poll"),
                    ("checkin", "Check-in"),
                    ("feelings", "Feelings"),
                    ("share", "Share"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
