# Generated by Django 5.2.3 on 2026-03-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_alter_post_privacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media_url",
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="posts/")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="feed.post",
                    ),
                ),
            ],
            options={
                "db_table": "post_media",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
