# Generated by Django 5.2.3 on 2026-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_remove_post_media_url_postmedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postmedia",
            name="image",
        ),
        migrations.AddField(
            model_name="postmedia",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
