# Generated by Django 5.2.3 on 2026-04-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_alter_post_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("poll", "Poll"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
