# Generated by Django 5.2.3 on 2026-04-12 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_alter_post_post_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="thumbnail_variant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reel_thumbnail",
                to="feed.mediavariant",
            ),
        ),
    ]
