# Generated by Django 5.2.3 on 2026-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("search_type", models.CharField(default="all", max_length=20)),
                ("results_count", models.IntegerField(default=0)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_history",
                "ordering": ["-searched_at"],
            },
        ),
    ]
