# Generated by Django 5.2.3 on 2026-03-27 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("profile_update", "Profile Update"),
                            ("profile_picture_changed", "Profile Picture Changed"),
                            ("cover_photo_changed", "Cover Photo Changed"),
                            ("new_message", "New Message"),
                            ("mention_notification", "Mention Notification"),
                            ("tag_notification", "Tag Notification"),
                            ("new_like", "New Like"),
                            ("new_comment", "New Comment"),
                            ("comment_reply", "Comment Reply"),
                            ("new_share", "New Share"),
                            ("reaction_update", "Reaction Update"),
                            ("friend_request", "Friend Request"),
                            ("friend_request_accepted", "Friend Request Accepted"),
                            ("group_invitation", "Group Invitation"),
                            ("group_post_notification", "Group Post Notification"),
                            ("event_invitation", "Event Invitation"),
                            ("event_reminder", "Event Reminder"),
                            ("follower_milestone", "Follower Milestone"),
                            ("post_milestone", "Post Milestone"),
                            ("achievement_badge", "Achievement Badge"),
                            ("login_alert", "Login Alert"),
                            ("two_factor_enabled", "Two-Factor Authentication Enabled"),
                            (
                                "two_factor_disabled",
                                "Two-Factor Authentication Disabled",
                            ),
                            ("security_alert", "Security Alert"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(
                        help_text="Use {{ subscriber.email }} for dynamic content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("follow", "Follow"),
                            ("message", "Message"),
                            ("group_invite", "Group Invite"),
                            ("event_reminder", "Event Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("related_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "related_model",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotifyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("profile_update", "Profile Update"),
                            ("profile_picture_changed", "Profile Picture Changed"),
                            ("cover_photo_changed", "Cover Photo Changed"),
                            ("new_message", "New Message"),
                            ("mention_notification", "Mention Notification"),
                            ("tag_notification", "Tag Notification"),
                            ("new_like", "New Like"),
                            ("new_comment", "New Comment"),
                            ("comment_reply", "Comment Reply"),
                            ("new_share", "New Share"),
                            ("reaction_update", "Reaction Update"),
                            ("friend_request", "Friend Request"),
                            ("friend_request_accepted", "Friend Request Accepted"),
                            ("group_invitation", "Group Invitation"),
                            ("group_post_notification", "Group Post Notification"),
                            ("event_invitation", "Event Invitation"),
                            ("event_reminder", "Event Reminder"),
                            ("follower_milestone", "Follower Milestone"),
                            ("post_milestone", "Post Milestone"),
                            ("achievement_badge", "Achievement Badge"),
                            ("login_alert", "Login Alert"),
                            ("two_factor_enabled", "Two-Factor Authentication Enabled"),
                            (
                                "two_factor_disabled",
                                "Two-Factor Authentication Disabled",
                            ),
                            ("security_alert", "Security Alert"),
                        ],
                        default="custom",
                        help_text="Template type for this notification",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("resend", "Resend"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("channel", models.CharField(default="email", max_length=50)),
                (
                    "priority",
                    models.CharField(
                        default="normal",
                        help_text="Email priority level",
                        max_length=20,
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Send duration in milliseconds", null=True
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "resend_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Manual resend attempts"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "notify_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
