# Generated by Django 5.2.3 on 2026-03-21 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acted_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notifylog",
            index=models.Index(fields=["status"], name="idx_notify_status"),
        ),
        migrations.AddIndex(
            model_name="notifylog",
            index=models.Index(fields=["recipient_email"], name="idx_notify_recipient"),
        ),
        migrations.AddIndex(
            model_name="notifylog",
            index=models.Index(
                fields=["status", "created_at"], name="idx_notify_status_created"
            ),
        ),
    ]
